# =============================================================================
# NOTE: Edit DOMAIN_PROD in deploy/.env if copying to another repo
# =============================================================================
version: "3.9"

services:
  app:
    image: ${APP_IMAGE}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app-prod.rule=Host(`${DOMAIN_PROD}`)"
      - "traefik.http.routers.app-prod.entrypoints=websecure"
      - "traefik.http.routers.app-prod.tls.certresolver=letsencrypt"
      - "traefik.http.services.app-prod.loadbalancer.server.port=80"
      - "traefik.http.middlewares.redirect-to-my-portfolio-prod.redirectregex.regex=^https?://[^/]+/(.*)"
      - "traefik.http.middlewares.redirect-to-my-portfolio-prod.redirectregex.replacement=https://portfolio.tribalorigin.com/$${1}"
      - "traefik.http.middlewares.redirect-to-my-portfolio-prod.redirectregex.permanent=true"
      - "traefik.http.routers.app-prod-redirect.rule=Host(`tribalorigin.com`)"
      - "traefik.http.routers.app-prod-redirect.entrypoints=websecure"
      - "traefik.http.routers.app-prod-redirect.tls.certresolver=letsencrypt"
      - "traefik.http.routers.app-prod-redirect.middlewares=redirect-to-my-portfolio-prod"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - prod
    restart: unless-stopped

networks:
  prod:
    external: true
